#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/install-self-host.sh --public-ip IP --funcom-token TOKEN --admin-password PASSWORD --steam-dir PATH [options]

Creates or updates the local DASH env file, generates RabbitMQ TLS material through
scripts/populate-local-env.sh, and optionally starts a single Survival_1 stack.

Required unless already set in the target env file:
  --public-ip IP              Public address clients should use.
  --funcom-token TOKEN        Funcom self-hosting token to write into the env.
  --admin-password PASSWORD   Admin panel token/password to write into the env.
  --steam-dir PATH            Official Steam tool install directory.

Options:
  --env-file PATH             Env file to create/update. Default: .env
  --world-name NAME           WORLD_NAME value. Default: Dune Awakening Server
  --world-unique-name NAME    WORLD_UNIQUE_NAME value. Default: generated by populate-local-env.sh
  --world-region REGION       WORLD_REGION value. Default: North America
  --server-login-password PW  Player login password. Default: same as --admin-password
  --no-server-login-password  Leave DUNE_SERVER_LOGIN_PASSWORD empty.
  --start-single-map          Load images, bootstrap the DB, and start Survival_1 plus the admin panel.
  --skip-single-partition     Do not prune extra Survival_1 partitions during --start-single-map.
  -h, --help                  Show this help.

Environment variables can provide defaults:
  DASH_PUBLIC_IP, DASH_FUNCOM_TOKEN, DASH_ADMIN_PASSWORD,
  DUNE_STEAM_SERVER_DIR, DASH_SERVER_LOGIN_PASSWORD
USAGE
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_value() {
  local option="$1"
  local value="${2:-}"
  [[ -n "$value" ]] || die "$option requires a non-empty value"
}

reject_multiline() {
  local name="$1"
  local value="$2"
  case "$value" in
    *$'\n'*|*$'\r'*)
      die "$name must be a single-line value"
      ;;
  esac
}

get_env_value() {
  local key="$1"
  local file="$2"
  [[ -f "$file" ]] || return 0
  awk -F= -v key="$key" '
    $0 ~ "^[[:space:]]*" key "=" {
      sub(/^[^=]*=/, "")
      gsub(/^["'\''"]|["'\''"]$/, "")
      print
      exit
    }
  ' "$file"
}

set_env_value() {
  local key="$1"
  local value="$2"
  local file="$3"
  local tmp

  reject_multiline "$key" "$value"
  tmp="$(mktemp)"
  awk -v key="$key" -v value="$value" '
    BEGIN { replaced = 0 }
    $0 ~ "^[[:space:]]*" key "=" {
      print key "=" value
      replaced = 1
      next
    }
    { print }
    END {
      if (!replaced) {
        print key "=" value
      }
    }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

env_file=".env"
public_ip="${DASH_PUBLIC_IP:-}"
funcom_token="${DASH_FUNCOM_TOKEN:-}"
admin_password="${DASH_ADMIN_PASSWORD:-}"
steam_dir="${DUNE_STEAM_SERVER_DIR:-}"
world_name="${DASH_WORLD_NAME:-}"
world_unique_name="${DASH_WORLD_UNIQUE_NAME:-}"
world_region="${DASH_WORLD_REGION:-}"
server_login_password="${DASH_SERVER_LOGIN_PASSWORD:-__same_as_admin__}"
start_single_map=false
skip_single_partition=false

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --env-file)
      require_value "$1" "${2:-}"
      env_file="$2"
      shift 2
      ;;
    --public-ip)
      require_value "$1" "${2:-}"
      public_ip="$2"
      shift 2
      ;;
    --funcom-token)
      require_value "$1" "${2:-}"
      funcom_token="$2"
      shift 2
      ;;
    --admin-password)
      require_value "$1" "${2:-}"
      admin_password="$2"
      shift 2
      ;;
    --steam-dir)
      require_value "$1" "${2:-}"
      steam_dir="$2"
      shift 2
      ;;
    --world-name)
      require_value "$1" "${2:-}"
      world_name="$2"
      shift 2
      ;;
    --world-unique-name)
      require_value "$1" "${2:-}"
      world_unique_name="$2"
      shift 2
      ;;
    --world-region)
      require_value "$1" "${2:-}"
      world_region="$2"
      shift 2
      ;;
    --server-login-password)
      require_value "$1" "${2:-}"
      server_login_password="$2"
      shift 2
      ;;
    --no-server-login-password)
      server_login_password=""
      shift
      ;;
    --start-single-map)
      start_single_map=true
      shift
      ;;
    --skip-single-partition)
      skip_single_partition=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

[[ "$env_file" != /* ]] && env_file="$repo_root/$env_file"

if [[ -f "$env_file" ]]; then
  printf 'Updating existing env file: %s\n' "$env_file"
else
  printf 'Creating env file and RabbitMQ TLS material: %s\n' "$env_file"
fi
./scripts/populate-local-env.sh "$env_file"

public_ip="${public_ip:-$(get_env_value EXTERNAL_ADDRESS "$env_file")}"
funcom_token="${funcom_token:-$(get_env_value FLS_SECRET "$env_file")}"
admin_password="${admin_password:-$(get_env_value DUNE_ADMIN_TOKEN "$env_file")}"
steam_dir="${steam_dir:-$(get_env_value DUNE_STEAM_SERVER_DIR "$env_file")}"
world_name="${world_name:-$(get_env_value WORLD_NAME "$env_file")}"
world_unique_name="${world_unique_name:-$(get_env_value WORLD_UNIQUE_NAME "$env_file")}"
world_region="${world_region:-$(get_env_value WORLD_REGION "$env_file")}"

if [[ -z "$funcom_token" && -t 0 ]]; then
  read -r -s -p "Funcom self-hosting token: " funcom_token
  printf '\n'
fi

[[ -n "$public_ip" && "$public_ip" != "127.0.0.1" ]] || die "set --public-ip to a public or routable address"
[[ -n "$funcom_token" ]] || die "set --funcom-token or DASH_FUNCOM_TOKEN"
[[ -n "$admin_password" && "$admin_password" != "change-me-admin-token" ]] || die "set --admin-password or DASH_ADMIN_PASSWORD"
[[ -n "$steam_dir" && "$steam_dir" != "/path/to/Steam/steamapps/common/Dune Awakening Self-Hosted Server" ]] || die "set --steam-dir to the Steam tool install path"
world_name="${world_name:-Dune Awakening Server}"
world_region="${world_region:-North America}"
[[ -n "$world_unique_name" ]] || die "WORLD_UNIQUE_NAME is empty; rerun scripts/populate-local-env.sh or pass --world-unique-name"

if [[ "$server_login_password" == "__same_as_admin__" ]]; then
  server_login_password="$admin_password"
fi

set_env_value DUNE_STEAM_SERVER_DIR "$steam_dir" "$env_file"
set_env_value WORLD_NAME "$world_name" "$env_file"
set_env_value WORLD_UNIQUE_NAME "$world_unique_name" "$env_file"
set_env_value WORLD_REGION "$world_region" "$env_file"
set_env_value DUNE_SERVER_DISPLAY_NAME "$world_name" "$env_file"
set_env_value DUNE_SERVER_LOGIN_PASSWORD "$server_login_password" "$env_file"
set_env_value FLS_SECRET "$funcom_token" "$env_file"
set_env_value DUNE_ADMIN_TOKEN "$admin_password" "$env_file"
set_env_value DUNE_ADMIN_REQUIRE_TOKEN true "$env_file"
set_env_value EXTERNAL_ADDRESS "$public_ip" "$env_file"
set_env_value GAME_RMQ_PUBLIC_HOST "$public_ip" "$env_file"
set_env_value DUNE_ANNOUNCE_HOST_WORKSPACE "$repo_root" "$env_file"
set_env_value DUNE_RESTART_HOST_WORKSPACE "$repo_root" "$env_file"
set_env_value DUNE_ANNOUNCE_RMQ_USER "bgd.$world_unique_name.duneadmin.admin" "$env_file"

printf 'Wrote DASH env settings for public address %s\n' "$public_ip"
printf 'Admin panel token auth is enabled; use the configured admin password as X-Admin-Token.\n'

if [[ "$start_single_map" != true ]]; then
  cat <<EOF

Configuration complete. Next checks:
  ./scripts/bootstrap-checklist.sh "$env_file"
  ./scripts/preflight.sh "$env_file"

To have this script start a single-map stack, rerun it with --start-single-map.
EOF
  exit 0
fi

[[ -d "$steam_dir" ]] || die "Steam tool directory does not exist: $steam_dir"

rc=0
./scripts/check-steam-update.sh "$env_file" --write-env || rc=$?
if [[ $rc -gt 1 ]]; then
  die "check-steam-update.sh failed (exit $rc)"
fi
./scripts/load-images.sh "$env_file"
docker compose --env-file "$env_file" config --quiet
docker compose --env-file "$env_file" up -d postgres admin-rmq game-rmq
docker compose --env-file "$env_file" run --rm db-init
docker compose --env-file "$env_file" up -d rmq-auth-shim text-router gateway director

if [[ "$skip_single_partition" != true ]]; then
  ./scripts/single-survival-partition.sh "$env_file"
else
  docker compose --env-file "$env_file" up -d survival
fi

docker compose --env-file "$env_file" up -d admin-panel
./scripts/status.sh "$env_file"
admin_port="$(get_env_value DUNE_ADMIN_HOST_PORT "$env_file" || true)"

cat <<EOF

Single-map install started.
Admin panel: http://127.0.0.1:${admin_port:-18080}/
Use the configured admin password as the admin token when prompted.
EOF
